### ISSUE TITLE
ToDo: Set up initial stuffs!

### ISSUE THREAD

**Issue by Guard13007** [TotallyNotMonopoly/Lazulopoly#1]
- [ ] set up secrets!
- [ ] set up instructions on install / running
- [ ] remember migrations expect an environment to be specified!!
